name: clothesmatch
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  appinio_swiper: ^2.1.0
  flutter_card_swiper: ^7.0.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
