name: clothesmatch
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  appinio_swiper: ^2.1.0
  flutter_card_swiper: ^7.0.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  image_picker: ^1.1.0
  permission_handler: ^11.3.1
  firebase_storage: ^11.7.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/afglogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/afglogo.png"
    background_color: "#fffafa"
    theme_color: "#fffafa"
  windows:
    generate: true
    image_path: "lib/afglogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/afglogo.png"

flutter:
  uses-material-design: true
